<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>org.pg</groupId>
    <artifactId>parent</artifactId>
    <version>3.0.0</version>
    <packaging>pom</packaging>

    <name>pg.parent</name>
    <description>Simple parent for org.pg group projects</description>
    <url>https://maven.apache.org</url>

    <properties>
        <java-version>25</java-version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Spring & Spring Boot-->
        <spring-framework-version>7.0.8</spring-framework-version>
        <spring-boot-starter-version>4.1.0</spring-boot-starter-version>
        <spring-cloud.version>2025.1.2</spring-cloud.version>

        <!-- Hibernate -->
        <hibernate-core.version>7.4.5.Final</hibernate-core.version>
        <hibernate-utils.version>3.9.4</hibernate-utils.version>

        <!-- Spring Doc -->
        <spring-doc.version>3.1.0</spring-doc.version>

        <!-- MONGO -->
        <mongo-embedded.version>4.22.0</mongo-embedded.version>

        <!-- AWS -->
        <aws-lib.version>1.12.797</aws-lib.version>

        <!-- JWT -->
        <jwt-api.version>0.13.0</jwt-api.version>

        <!-- HTTP -->
        <ok-http-client.version>5.4.0</ok-http-client.version>

        <!-- COMMONS -->
        <apache-commons.version>3.20.0</apache-commons.version>
        <beanio.version>2.1.0</beanio.version>

        <!-- POSTPROCESSORS -->
        <lombok.version>1.18.46</lombok.version>

        <!-- UTILS -->
        <kaczmarzyk-specification.version>2.6.3</kaczmarzyk-specification.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- 3rd party libraries-->
            <dependency>
                <groupId>net.kaczmarzyk</groupId>
                <artifactId>specification-arg-resolver</artifactId>
                <version>${kaczmarzyk-specification.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jwt-api.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jwt-api.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jwt-api.version}</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${ok-http-client.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk</artifactId>
                <version>${aws-lib.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${spring-doc.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-common</artifactId>
                <version>${spring-doc.version}</version>
            </dependency>
            <dependency>
                <groupId>de.flapdoodle.embed</groupId>
                <artifactId>de.flapdoodle.embed.mongo.spring30x</artifactId>
                <version>${mongo-embedded.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${apache-commons.version}</version>
            </dependency>
            <dependency>
                <groupId>org.hibernate.orm</groupId>
                <artifactId>hibernate-core</artifactId>
                <version>${hibernate-core.version}</version>
            </dependency>
            <dependency>
                <groupId>io.hypersistence</groupId>
                <artifactId>hypersistence-utils-hibernate-60</artifactId>
                <version>${hibernate-utils.version}</version>
            </dependency>
            <dependency>
                <groupId>org.beanio</groupId>
                <artifactId>beanio</artifactId>
                <version>${beanio.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.11.0</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <source>${java-version}</source>
                    <target>${java-version}</target>
                    <release>${java-version}</release>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>3.1.4</version>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub Paros998 Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/pg-personal-organization/pg-parent</url>
        </repository>
    </distributionManagement>

    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2</url>
        </repository>

        <repository>
            <id>github-pg-parent</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/pg-personal-organization/pg-parent</url>
        </repository>

        <repository>
            <id>github-pg.lib</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/pg-personal-organization/pg.lib</url>
        </repository>

        <repository>
            <id>github-pg.kafka</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/pg-personal-organization/pg.kafka</url>
        </repository>

        <repository>
            <id>github-pg.imports</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/pg-personal-organization/pg.imports</url>
        </repository>

        <repository>
            <id>github-pg.accounts</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/pg-personal-organization/pg.accounts</url>
        </repository>

        <repository>
            <id>github-pg-context-auth</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/pg-personal-organization/pg-context-auth</url>
        </repository>

        <repository>
            <id>github-pg.payments</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/pg-personal-organization/pg.payments</url>
        </repository>

        <repository>
            <id>github-pg.api-gateway</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/pg-personal-organization/pg.api-gateway</url>
        </repository>

    </repositories>

</project>
